language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0 QA=true
  - PLONE_VERSION=5.1 QA=true
matrix:
  fast_finish: true
install:
  - pip install -r requirements.txt
  - buildout -c plone-$PLONE_VERSION.x.cfg -N buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
  - bin/code-analysis
  - bin/test --all
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - dev@bluedynamics.com
