language: python
python: 2.7
env:
  - PLONE_VERSION=4.3 QA=true
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/code-analysis && bin/test
after_success:
  - test -v QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
