language: python
python: 2.7
python:
  - 2.6
  - 2.7
env:
  - PLONE=4.1
  - PLONE=4.2
  - PLONE=4.3
matrix:
  exclude:
    - python: 2.7
      env: PLONE=4.1
    - python: 2.6
      env: PLONE=4.2
    - python: 2.6
      env: PLONE=4.3
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/code-analysis && bin/test
after_success:
  - test -v QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
